CXX = C:/msys64/mingw64/bin/g++.exe
CXXFLAGS = -std=c++17 -Wall -Iglad/include -Iexternal/imgui -Iexternal/imgui/backends
LIBS = -lglfw3 -lopengl32 -lgdi32 -lpthread

SRCS = cubo.cpp \
       estado.cpp \
       busca.cpp \
       busca_largura.cpp \
       simetria.cpp \
       glad/src/glad.c \
       external/imgui/imgui.cpp \
       external/imgui/imgui_demo.cpp \
       external/imgui/imgui_draw.cpp \
       external/imgui/imgui_tables.cpp \
       external/imgui/imgui_widgets.cpp \
       external/imgui/backends/imgui_impl_glfw.cpp \
       external/imgui/backends/imgui_impl_opengl3.cpp

TARGET = cubo.exe

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CXX) $(CXXFLAGS) $(SRCS) $(LIBS) -o $(TARGET)

run: $(TARGET)
	./$(TARGET)

clean:
	rm -f $(TARGET)
